import 'dart:io';

import 'package:senter_premium/core/three_d/mesh_builder.dart';
import 'package:senter_premium/core/three_d/obj_format.dart';
import 'package:senter_premium/core/three_d/vec3.dart';

const body = 'body';
const grip = 'grip';
const gold = 'gold';
const head = 'head';
const reflector = 'reflector';
const lens = 'lens';
const button = 'button';

void main() {
  final builder = MeshBuilder()
    ..lathe(_profile(), segments: 56)
    ..box(const Vec3(0.0, 0.20, -0.065), const Vec3(0.16, 0.285, 0.065), button)
    ..box(const Vec3(0.02, 0.28, -0.05), const Vec3(0.14, 0.295, 0.05), button);

  final mesh = builder.build();
  final obj = writeObj(
    mesh,
    header:
        'Senter Premium — generated by tool/generate_flashlight_model.dart\n'
        'Triangles: ${mesh.triangleCount}\n'
        'Materials: ${mesh.materialNames.join(', ')}',
  );

  final file = File('assets/models/flashlight.obj')
    ..parent.createSync(recursive: true)
    ..writeAsStringSync(obj);
  stdout.writeln(
    'Wrote ${file.path} (${mesh.triangleCount} triangles, '
    '${(file.lengthSync() / 1024).toStringAsFixed(1)} KB)',
  );
}

List<ProfilePoint> _profile() {
  final points = <ProfilePoint>[
    const ProfilePoint(-1.20, 0.00, body),
    const ProfilePoint(-1.20, 0.20, body),
    const ProfilePoint(-1.17, 0.26, body),
    const ProfilePoint(-1.05, 0.26, body),
    const ProfilePoint(-1.02, 0.24, body),
    const ProfilePoint(-0.92, 0.24, grip),
  ];

  const ridges = 8;
  const gripStart = -0.92;
  const pitch = 0.1;
  for (var i = 0; i < ridges; i++) {
    final x = gripStart + i * pitch;
    points
      ..add(ProfilePoint(x + 0.015, 0.254, grip))
      ..add(ProfilePoint(x + 0.075, 0.254, grip))
      ..add(ProfilePoint(x + 0.09, 0.24, grip));
    if (i < ridges - 1) points.add(ProfilePoint(x + pitch, 0.24, grip));
  }

  points.addAll(const [
    ProfilePoint(-0.12, 0.24, body),
    ProfilePoint(0.20, 0.24, gold),
    ProfilePoint(0.205, 0.256, gold),
    ProfilePoint(0.255, 0.256, gold),
    ProfilePoint(0.26, 0.24, body),
    ProfilePoint(0.36, 0.24, head),
    ProfilePoint(0.50, 0.275, head),
    ProfilePoint(0.62, 0.33, head),
    ProfilePoint(0.72, 0.40, head),
    ProfilePoint(0.74, 0.42, head),
    ProfilePoint(0.86, 0.42, gold),
    ProfilePoint(0.93, 0.42, gold),
    ProfilePoint(0.95, 0.40, gold),
    ProfilePoint(0.95, 0.365, reflector),
    ProfilePoint(0.90, 0.365, lens),
    ProfilePoint(0.90, 0.00, lens),
  ]);
  return points;
}
